#!/usr/bin/env bash
ml python/3.12.3
# to run swim
source dependencies/swim/project/activate_foote

# create venv if it doesn't exist and install the package in editable mode
if [ ! -d "venv" ]; then
    python3 -m venv venv
    venv/bin/pip install -e .
fi

source venv/bin/activate