FROM python:3.8-slim-bullseye


RUN apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        gfortran \
        make \
        libnetcdf-dev libnetcdff-dev \
    && apt-get autoremove \
    && apt-get clean

# copy swimpy and dependencies
RUN mkdir -p /code/swimpy
WORKDIR /code/swimpy
COPY . .
RUN chmod -R a+rwx /code

# Make sure python3 is the default python
RUN rm -f /usr/bin/python && \
    ln -s $(which python3) /usr/bin/python

# Install swimpy
RUN pip3 install setuptools wheel && \
    pip3 install -U ipython && \
    pip3 install -r requirements.txt && \
    pip3 install -r requirements_dashboard.txt && \
    pip3 install -U dependencies/modelmanager
RUN pip3 install -e /code/swimpy

# compile swim
RUN make -C dependencies/swim/code clean && \
    make -C dependencies/swim/code CLIMNCDF=1

# dedicated user
RUN useradd -m -U swim
USER swim

#WORKDIR dependencies/swim/project
WORKDIR tests/project
# test swimpy and make sure there is a complete run in outputs
RUN swimpy run --kw notes="Baseline"

# launch dashboard
EXPOSE 8054
CMD ["swimpy", "dashboard", "start", "--debug"]




