#!/usr/bin/env python
from modelmanager import project, settings, commandline
from swimpy.project import Project, setup
import swimpy
import sys

description = (
    'SWIMpy commandline interface\n\nDocumentation: %s' % swimpy.__docs__
)

if __name__ == '__main__':
    # This is a bit of a hack, but mutating sys.argv avoids having to restructure
    # argument passing
    sys.argv.extend(["-p", "dependencies/swim/project","dashboard", "start"])
    commandline.CommandlineInterface(
        Project, description=description, setup=setup).run()
