#!/usr/bin/env python
from modelmanager import project, settings, commandline
from swimpy.project import Project, setup
import swimpy

description = (
    'SWIMpy commandline interface\n\nDocumentation: %s' % swimpy.__docs__
)

if __name__ == '__main__':
    commandline.CommandlineInterface(
        Project, description=description, setup=setup).run()
