#!/usr/bin/env python
import sys, os
from modelmanager import project, settings, commandline

# make sure swimpy is not picked up from the current directory
for p in ["", ".", os.getcwd()]:
    if p in sys.path:
        sys.path.remove(p)

from swimpy.project import Project, setup
import swimpy

description = (
    'SWIMpy commandline interface\n\nDocumentation: %s' % swimpy.__docs__
)

if __name__ == '__main__':
    commandline.CommandlineInterface(
        Project, description=description, setup=setup).run()
